[package]
name = "eve-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
ucs2 = "0.3.2"
log = { workspace = true }

[dev-dependencies]
test-log = "0.2.11"
env_logger = "0.10.0"